const htmlWeather = (body) => {
    const section = document.createElement('section');
    section.setAttribute('id', 'weatherCont');
    const sectionCurr = document.createElement('section');
    sectionCurr.setAttribute('id', 'sectionCurr');
    const sectionFirst = document.createElement('section');
    sectionFirst.setAttribute('id', 'sectionFirst');
    const sectionSecond = document.createElement('section');
    sectionSecond.setAttribute('id', 'sectionSecond');
    const sectionThird = document.createElement('section');
    sectionThird.setAttribute('id', 'sectionThird');
    const sectionCurrText = document.createElement('section');
    sectionCurrText.setAttribute('id', 'sectionCurrText');
    const tempNow = document.createElement('p');
    tempNow.setAttribute('id', 'tempNow');
    const img = document.createElement('img');
    img.setAttribute('id', 'icon')
    const text = document.createElement('p');
    text.setAttribute('id', 'text');
    const feelsLike = document.createElement('p');
    feelsLike.setAttribute('id', 'feelsLike');
    const wind = document.createElement('p');
    wind.setAttribute('id', 'wind');
    const humidity = document.createElement('p');
    humidity.setAttribute('id', 'humidity');
    const forecastDay = document.createElement('p');
    forecastDay.setAttribute('id', 'forecastDay');
    const forecastTemp = document.createElement('p');
    forecastTemp.setAttribute('id', 'forecastTemp');
    const forecastIcon = document.createElement('img');
    forecastIcon.setAttribute('id', 'forecastIcon');
    const forecastDaySecond = document.createElement('p');
    forecastDaySecond.setAttribute('id', 'forecastDaySecond');
    const forecastTempSecond = document.createElement('p');
    forecastTempSecond.setAttribute('id', 'forecastTempSecond');
    const forecastIconSecond = document.createElement('img');
    forecastIconSecond.setAttribute('id', 'forecastIconSecond');
    const forecastDayThird = document.createElement('p');
    forecastDayThird.setAttribute('id', 'forecastDayThird');
    const forecastTempThird = document.createElement('p');
    forecastTempThird.setAttribute('id', 'forecastTempThird');
    const forecastIconThird = document.createElement('img');
    forecastIconThird.setAttribute('id', 'forecastIconThird');
    const sectionLocal = document.createElement('section');
    sectionLocal.setAttribute('id', 'sectionLocal');
    const latitude = document.createElement('p');
    latitude.setAttribute('id', 'lat');
    const longitude = document.createElement('p');
    longitude.setAttribute('id', 'long');
    section.appendChild(sectionCurr);
    section.appendChild(sectionFirst);
    section.appendChild(sectionSecond);
    section.appendChild(sectionThird);
    sectionCurr.appendChild(tempNow);
    sectionCurr.appendChild(sectionCurrText);
    sectionCurrText.appendChild(img);
    sectionCurrText.appendChild(text);
    sectionCurrText.appendChild(feelsLike);
    sectionCurrText.appendChild(wind);
    sectionCurrText.appendChild(humidity);
    sectionFirst.appendChild(forecastDay);
    sectionFirst.appendChild(forecastTemp);
    sectionFirst.appendChild(forecastIcon);
    sectionSecond.appendChild(forecastDaySecond);
    sectionSecond.appendChild(forecastTempSecond);
    sectionSecond.appendChild(forecastIconSecond);
    sectionThird.appendChild(forecastDayThird);
    sectionThird.appendChild(forecastTempThird);
    sectionThird.appendChild(forecastIconThird);
    sectionLocal.appendChild(latitude);
    sectionLocal.appendChild(longitude);
    body.appendChild(section);
    body.appendChild(sectionLocal);
}
export default htmlWeather;